[package]
name = "rust-wildbow-scraper"
version = "1.0.0"
authors = ["Nico Hickman <nicohman@demenses.net>"]

[dependencies]
reqwest = "0.9.3"
select = "0.4.2"
gen-epub-book = "2.2.0"
chrono = "0.4"
url = "1.7.0"
argparse = "0.2.2"
